apiVersion: v1
kind: Service
metadata:
  name: {{ include "spegel.fullname" . }}
  labels:
    {{- include "spegel.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "spegel.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.service.metrics.port }}
      targetPort: metrics
      protocol: TCP
---
{{- if .Values.spegel.bootstrap.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spegel.fullname" . }}-bootstrap
  labels:
    {{- include "spegel.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    {{- include "spegel.selectorLabels" . | nindent 4 }}
  ports:
    - name: registry
      port: {{ .Values.service.registry.port }}
      targetPort: registry
      nodePort: {{ .Values.service.registry.nodePort }}
      protocol: TCP
{{- end }}